version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build:
    docker:
      - image: 'node:10.15.3'
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync ./build/ arn:aws:s3:::katieandzach.wedding --delete

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
              branches:
                ignore: /.*/
              tags:
                only: /.*/
      - deploy:
          requires:
            - build
          context: aws-context
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

